server:
  port: 9090

spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=jumarket
    username: postgres
    password: 123
  flyway:
    default-schema: jumarket